name: Auto Merge Only for Im-gowtham-cd

on:
  pull_request:
    types: [opened, synchronize, reopened]   # ✅ fixed typo

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.event.pull_request.user.login == 'Im-gowtham-cd' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Enable Auto Merge
        run: gh pr merge ${{ github.event.pull_request.number }} \
              --repo ${{ github.repository }} \
              --squash \
              --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}